// Nigeria Location Data - All 36 States and Local Government Areas

export interface LocalGovernmentArea {
  id: string;
  name: string;
}

export interface State {
  id: string;
  name: string;
  capital: string;
  lgas: LocalGovernmentArea[];
}

export interface Country {
  id: string;
  name: string;
  code: string;
  states: State[];
}

// Nigeria - All 36 States and FCT with Local Government Areas
export const nigeriaLocationData: Country = {
  id: 'ng',
  name: 'Nigeria',
  code: 'NG',
  states: [
    {
      id: 'abia',
      name: 'Abia',
      capital: 'Umuahia',
      lgas: [
        { id: 'abia-1', name: 'Aba North' },
        { id: 'abia-2', name: 'Aba South' },
        { id: 'abia-3', name: 'Arochukwu' },
        { id: 'abia-4', name: 'Bende' },
        { id: 'abia-5', name: 'Ikwano' },
        { id: 'abia-6', name: 'Isiala Ngwa North' },
        { id: 'abia-7', name: 'Isiala Ngwa South' },
        { id: 'abia-8', name: 'Isuikwuato' },
        { id: 'abia-9', name: 'Obi Ngwa' },
        { id: 'abia-10', name: 'Ohafia' },
        { id: 'abia-11', name: 'Osisioma' },
        { id: 'abia-12', name: 'Ugwunagbo' },
        { id: 'abia-13', name: 'Ukwa East' },
        { id: 'abia-14', name: 'Ukwa West' },
        { id: 'abia-15', name: 'Umuahia North' },
        { id: 'abia-16', name: 'Umuahia South' },
        { id: 'abia-17', name: 'Umune 1' },
      ]
    },
    {
      id: 'adamawa',
      name: 'Adamawa',
      capital: 'Yola',
      lgas: [
        { id: 'adamawa-1', name: 'Demsa' },
        { id: 'adamawa-2', name: 'Fufore' },
        { id: 'adamawa-3', name: 'Ganye' },
        { id: 'adamawa-4', name: 'Girei' },
        { id: 'adamawa-5', name: 'Gombi' },
        { id: 'adamawa-6', name: 'Guyuk' },
        { id: 'adamawa-7', name: 'Hong' },
        { id: 'adamawa-8', name: 'Jada' },
        { id: 'adamawa-9', name: 'Lamurde' },
        { id: 'adamawa-10', name: 'Madagali' },
        { id: 'adamawa-11', name: 'Maiha' },
        { id: 'adamawa-12', name: 'Mayo Belwa' },
        { id: 'adamawa-13', name: 'Michika' },
        { id: 'adamawa-14', name: 'Mubi North' },
        { id: 'adamawa-15', name: 'Mubi South' },
        { id: 'adamawa-16', name: 'Numan' },
        { id: 'adamawa-17', name: 'Shelleng' },
        { id: 'adamawa-18', name: 'Song' },
        { id: 'adamawa-19', name: 'Toungo' },
        { id: 'adamawa-20', name: 'Yola North' },
        { id: 'adamawa-21', name: 'Yola South' },
      ]
    },
    {
      id: 'akwa-ibom',
      name: 'Akwa Ibom',
      capital: 'Uyo',
      lgas: [
        { id: 'akwa-ibom-1', name: 'Abak' },
        { id: 'akwa-ibom-2', name: 'Eastern Obolo' },
        { id: 'akwa-ibom-3', name: 'Eket' },
        { id: 'akwa-ibom-4', name: 'Esit Eket' },
        { id: 'akwa-ibom-5', name: 'Essien Udim' },
        { id: 'akwa-ibom-6', name: 'Etim Ekpo' },
        { id: 'akwa-ibom-7', name: 'Etpo Anang' },
        { id: 'akwa-ibom-8', name: 'Ibesikpo Asutan' },
        { id: 'akwa-ibom-9', name: 'Ibiono Ibom' },
        { id: 'akwa-ibom-10', name: 'Ika' },
        { id: 'akwa-ibom-11', name: 'Ikono' },
        { id: 'akwa-ibom-12', name: 'Ikot Ekpene' },
        { id: 'akwa-ibom-13', name: 'Ini' },
        { id: 'akwa-ibom-14', name: 'Itu' },
        { id: 'akwa-ibom-15', name: 'Mbo' },
        { id: 'akwa-ibom-16', name: 'Mkpat Enin' },
        { id: 'akwa-ibom-17', name: 'Nsit Atai' },
        { id: 'akwa-ibom-18', name: 'Nsit Ibom' },
        { id: 'akwa-ibom-19', name: 'Nsit Ubium' },
        { id: 'akwa-ibom-20', name: 'Nwanie' },
        { id: 'akwa-ibom-21', name: 'Okobo' },
        { id: 'akwa-ibom-22', name: 'Onna' },
        { id: 'akwa-ibom-23', name: 'Oron' },
        { id: 'akwa-ibom-24', name: 'Oruk Anam' },
        { id: 'akwa-ibom-25', name: 'Udung Uko' },
        { id: 'akwa-ibom-26', name: 'Ukanafun' },
        { id: 'akwa-ibom-27', name: 'Uruan' },
        { id: 'akwa-ibom-28', name: 'Urue Offong/Oruko' },
        { id: 'akwa-ibom-29', name: 'Uyo' },
      ]
    },
    {
      id: 'anambra',
      name: 'Anambra',
      capital: 'Awka',
      lgas: [
        { id: 'anambra-1', name: 'Aguata' },
        { id: 'anambra-2', name: 'Anambra East' },
        { id: 'anambra-3', name: 'Anambra West' },
        { id: 'anambra-4', name: 'Anaocha' },
        { id: 'anambra-5', name: 'Awka North' },
        { id: 'anambra-6', name: 'Awka South' },
        { id: 'anambra-7', name: 'Ayamelum' },
        { id: 'anambra-8', name: 'Burutu' },
        { id: 'anambra-9', name: 'Dunkofin' },
        { id: 'anambra-10', name: 'Ekwusigo' },
        { id: 'anambra-11', name: 'Idemili North' },
        { id: 'anambra-12', name: 'Idemili South' },
        { id: 'anambra-13', name: 'Ihiala' },
        { id: 'anambra-14', name: 'Nnewi North' },
        { id: 'anambra-15', name: 'Nnewi South' },
        { id: 'anambra-16', name: 'Ogbaru' },
        { id: 'anambra-17', name: 'Onitsha North' },
        { id: 'anambra-18', name: 'Onitsha South' },
        { id: 'anambra-19', name: 'Orumba North' },
        { id: 'anambra-20', name: 'Orumba South' },
        { id: 'anambra-21', name: 'Oyi' },
      ]
    },
    {
      id: 'bauchi',
      name: 'Bauchi',
      capital: 'Bauchi',
      lgas: [
        { id: 'bauchi-1', name: 'Alkaleri' },
        { id: 'bauchi-2', name: 'Bauchi' },
        { id: 'bauchi-3', name: 'Bogoro' },
        { id: 'bauchi-4', name: 'Damban' },
        { id: 'bauchi-5', name: 'Darazo' },
        { id: 'bauchi-6', name: 'Dass' },
        { id: 'bauchi-7', name: 'Ganjuwa' },
        { id: 'bauchi-8', name: 'Giade' },
        { id: 'bauchi-9', name: 'Itas/Gadau' },
        { id: 'bauchi-10', name: 'Jama\'are' },
        { id: 'bauchi-11', name: 'Katagum' },
        { id: 'bauchi-12', name: 'Kirfi' },
        { id: 'bauchi-13', name: 'Misau' },
        { id: 'bauchi-14', name: 'Ningi' },
        { id: 'bauchi-15', name: 'Shira' },
        { id: 'bauchi-16', name: 'Tafawa Balewa' },
        { id: 'bauchi-17', name: 'Toro' },
        { id: 'bauchi-18', name: 'Warji' },
        { id: 'bauchi-19', name: 'Zaki' },
      ]
    },
    {
      id: 'bayelsa',
      name: 'Bayelsa',
      capital: 'Yenagoa',
      lgas: [
        { id: 'bayelsa-1', name: 'Brass' },
        { id: 'bayelsa-2', name: 'Ekeremor' },
        { id: 'bayelsa-3', name: 'Kolokuma/Opokuma' },
        { id: 'bayelsa-4', name: 'Nembe' },
        { id: 'bayelsa-5', name: 'Ogbia' },
        { id: 'bayelsa-6', name: 'Sagbama' },
        { id: 'bayelsa-7', name: 'Southern Ijaw' },
        { id: 'bayelsa-8', name: 'Yenagoa' },
      ]
    },
    {
      id: 'benue',
      name: 'Benue',
      capital: 'Makurdi',
      lgas: [
        { id: 'benue-1', name: 'Agatu' },
        { id: 'benue-2', name: 'Apa' },
        { id: 'benue-3', name: 'Ado' },
        { id: 'benue-4', name: 'Buruku' },
        { id: 'benue-5', name: 'Etungo' },
        { id: 'benue-6', name: 'Gwer East' },
        { id: 'benue-7', name: 'Gwer West' },
        { id: 'benue-8', name: 'Katsina-Ala' },
        { id: 'benue-9', name: 'Konshisha' },
        { id: 'benue-10', name: 'Kwande' },
        { id: 'benue-11', name: 'Logo' },
        { id: 'benue-12', name: 'Makurdi' },
        { id: 'benue-13', name: 'Obi' },
        { id: 'benue-14', name: 'Ogbadibo' },
        { id: 'benue-15', name: 'Oju' },
        { id: 'benue-16', name: 'Okpokwu' },
        { id: 'benue-17', name: 'Ohimini' },
        { id: 'benue-18', name: 'Oturkpo' },
        { id: 'benue-19', name: 'Tarka' },
        { id: 'benue-20', name: 'Ukum' },
        { id: 'benue-21', name: 'Ushongo' },
        { id: 'benue-22', name: 'Vandeikya' },
      ]
    },
    {
      id: 'borno',
      name: 'Borno',
      capital: 'Maiduguri',
      lgas: [
        { id: 'borno-1', name: 'Abadam' },
        { id: 'borno-2', name: 'Askira/Uba' },
        { id: 'borno-3', name: 'Bama' },
        { id: 'borno-4', name: 'Bayo' },
        { id: 'borno-5', name: 'Birom' },
        { id: 'borno-6', name: 'Chibok' },
        { id: 'borno-7', name: 'Damboa' },
        { id: 'borno-8', name: 'Dikwa' },
        { id: 'borno-9', name: 'Gwoza' },
        { id: 'borno-10', name: 'Hawul' },
        { id: 'borno-11', name: 'Jere' },
        { id: 'borno-12', name: 'Kaga' },
        { id: 'borno-13', name: 'Kala/Balge' },
        { id: 'borno-14', name: 'Konduga' },
        { id: 'borno-15', name: 'Kukawa' },
        { id: 'borno-16', name: 'K嫁/Magumeri' },
        { id: 'borno-17', name: 'Maiduguri' },
        { id: 'borno-18', name: 'Marte' },
        { id: 'borno-19', name: 'Monguno' },
        { id: 'borno-20', name: 'Ngala' },
        { id: 'borno-21', name: 'Nganzai' },
        { id: 'borno-22', name: 'Shani' },
      ]
    },
    {
      id: 'cross-river',
      name: 'Cross River',
      capital: 'Calabar',
      lgas: [
        { id: 'cross-river-1', name: 'Abi' },
        { id: 'cross-river-2', name: 'Akamkpa' },
        { id: 'cross-river-3', name: 'Akpabuyo' },
        { id: 'cross-river-4', name: 'Bakassi' },
        { id: 'cross-river-5', name: 'Bekwarra' },
        { id: 'cross-river-6', name: 'Biase' },
        { id: 'cross-river-7', name: 'Boki' },
        { id: 'cross-river-8', name: 'Calabar Municipal' },
        { id: 'cross-river-9', name: 'Calabar South' },
        { id: 'cross-river-10', name: 'Etung' },
        { id: 'cross-river-11', name: 'Ikom' },
        { id: 'cross-river-12', name: 'Obanliku' },
        { id: 'cross-river-13', name: 'Obudu' },
        { id: 'cross-river-14', name: 'Odukpani' },
        { id: 'cross-river-15', name: 'Ogoja' },
        { id: 'cross-river-16', name: 'Yakuur' },
        { id: 'cross-river-17', name: 'Yala' },
      ]
    },
    {
      id: 'delta',
      name: 'Delta',
      capital: 'Asaba',
      lgas: [
        { id: 'delta-1', name: 'Aniocha North' },
        { id: 'delta-2', name: 'Aniocha South' },
        { id: 'delta-3', name: 'Bomadi' },
        { id: 'delta-4', name: 'Burutu' },
        { id: 'delta-5', name: 'Ethiope East' },
        { id: 'delta-6', name: 'Ethiope West' },
        { id: 'delta-7', name: 'Ika North East' },
        { id: 'delta-8', name: 'Ika South' },
        { id: 'delta-9', name: 'Isoko North' },
        { id: 'delta-10', name: 'Isoko South' },
        { id: 'delta-11', name: 'Ndokwa East' },
        { id: 'delta-12', name: 'Ndokwa West' },
        { id: 'delta-13', name: 'Okpe' },
        { id: 'delta-14', name: 'Oshimili North' },
        { id: 'delta-15', name: 'Oshimili South' },
        { id: 'delta-16', name: 'Patani' },
        { id: 'delta-17', name: 'Sapele' },
        { id: 'delta-18', name: 'Udu' },
        { id: 'delta-19', name: 'Ughelli North' },
        { id: 'delta-20', name: 'Ughelli South' },
        { id: 'delta-21', name: 'Ukwuani' },
        { id: 'delta-22', name: 'Uvwie' },
        { id: 'delta-23', name: 'Warri Central' },
        { id: 'delta-24', name: 'Warri North' },
        { id: 'delta-25', name: 'Warri South' },
      ]
    },
    {
      id: 'ebonyi',
      name: 'Ebonyi',
      capital: 'Abakaliki',
      lgas: [
        { id: 'ebonyi-1', name: 'Abakaliki' },
        { id: 'ebonyi-2', name: 'Afikpo North' },
        { id: 'ebonyi-3', name: 'Afikpo South' },
        { id: 'ebonyi-4', name: 'Ceboli' },
        { id: 'ebonyi-5', name: 'Ebonyi' },
        { id: 'ebonyi-6', name: 'Ezza' },
        { id: 'ebonyi-7', name: 'Ezza South' },
        { id: 'ebonyi-8', name: 'Ikwo' },
        { id: 'ebonyi-9', name: 'Ishielu' },
        { id: 'ebonyi-10', name: 'Ivo' },
        { id: 'ebonyi-11', name: 'Izzi' },
        { id: 'ebonyi-12', name: 'Ohaozara' },
        { id: 'ebonyi-13', name: 'Ohaukwu' },
        { id: 'ebonyi-14', name: 'Onicha' },
      ]
    },
    {
      id: 'edo',
      name: 'Edo',
      capital: 'Benin City',
      lgas: [
        { id: 'edo-1', name: 'Akoko-Edo' },
        { id: 'edo-2', name: 'Egor' },
        { id: 'edo-3', name: 'Esan Central' },
        { id: 'edo-4', name: 'Esan North East' },
        { id: 'edo-5', name: 'Esan South East' },
        { id: 'edo-6', name: 'Esan West' },
        { id: 'edo-7', name: 'Etsako Central' },
        { id: 'edo-8', name: 'Etsako East' },
        { id: 'edo-9', name: 'Etsako West' },
        { id: 'edo-10', name: 'Igueben' },
        { id: 'edo-11', name: 'Ikpoba Okha' },
        { id: 'edo-12', name: 'Oredo' },
        { id: 'edo-13', name: 'Orhionmwon' },
        { id: 'edo-14', name: 'Ovia North East' },
        { id: 'edo-15', name: 'Ovia South West' },
        { id: 'edo-16', name: 'Owan East' },
        { id: 'edo-17', name: 'Owan West' },
        { id: 'edo-18', name: 'Uhunmwonde' },
      ]
    },
    {
      id: 'ekiti',
      name: 'Ekiti',
      capital: 'Ado-Ekiti',
      lgas: [
        { id: 'ekiti-1', name: 'Ado Ekiti' },
        { id: 'ekiti-2', name: 'Efon' },
        { id: 'ekiti-3', name: 'Ekiti East' },
        { id: 'ekiti-4', name: 'Ekiti South West' },
        { id: 'ekiti-5', name: 'Ekiti West' },
        { id: 'ekiti-6', name: 'Emure' },
        { id: 'ekiti-7', name: 'Gbonyin' },
        { id: 'ekiti-8', name: 'Ikere' },
        { id: 'ekiti-9', name: 'Ikole' },
        { id: 'ekiti-10', name: 'Ilejemeje' },
        { id: 'ekiti-11', name: 'Irepodun/Ifelodun' },
        { id: 'ekiti-12', name: 'Ise/Orun' },
        { id: 'ekiti-13', name: 'Moba' },
        { id: 'ekiti-14', name: 'Oye' },
        { id: 'ekiti-15', name: 'SqlEkiti' },
      ]
    },
    {
      id: 'enugu',
      name: 'Enugu',
      capital: 'Enugu',
      lgas: [
        { id: 'enugu-1', name: 'Aninri' },
        { id: 'enugu-2', name: 'Awgu' },
        { id: 'enugu-3', name: 'Enugu East' },
        { id: 'enugu-4', name: 'Enugu North' },
        { id: 'enugu-5', name: 'Enugu South' },
        { id: 'enugu-6', name: 'Ezeagu' },
        { id: 'enugu-7', name: 'Igbo Etiti' },
        { id: 'enugu-8', name: 'Igbo Eze North' },
        { id: 'enugu-9', name: 'Igbo Eze South' },
        { id: 'enugu-10', name: 'Isi Uzo' },
        { id: 'enugu-11', name: 'Nkanu East' },
        { id: 'enugu-12', name: 'Nkanu West' },
        { id: 'enugu-13', name: 'Nsukka' },
        { id: 'enugu-14', name: 'Oji River' },
        { id: 'enugu-15', name: 'Udenu' },
        { id: 'enugu-16', name: 'Udi' },
        { id: 'enugu-17', name: 'Uzo Uwani' },
      ]
    },
    {
      id: 'fct',
      name: 'Federal Capital Territory',
      capital: 'Abuja',
      lgas: [
        { id: 'fct-1', name: 'Abaji' },
        { id: 'fct-2', name: 'Abuja Municipal' },
        { id: 'fct-3', name: 'Bwari' },
        { id: 'fct-4', name: 'Dutse' },
        { id: 'fct-5', name: 'Gwagwalada' },
        { id: 'fct-6', name: 'Kuje' },
        { id: 'fct-7', name: 'Kwali' },
      ]
    },
    {
      id: 'gombe',
      name: 'Gombe',
      capital: 'Gombe',
      lgas: [
        { id: 'gombe-1', name: 'Balanga' },
        { id: 'gombe-2', name: 'Billiri' },
        { id: 'gombe-3', name: 'Dukku' },
        { id: 'gombe-4', name: 'Funakaye' },
        { id: 'gombe-5', name: 'Gombe' },
        { id: 'gombe-6', name: 'Kaltungo' },
        { id: 'gombe-7', name: 'Kwami' },
        { id: 'gombe-8', name: 'Nafada' },
        { id: 'gombe-9', name: 'Shongom' },
        { id: 'gombe-10', name: 'Yamaltu/Deba' },
      ]
    },
    {
      id: 'imo',
      name: 'Imo',
      capital: 'Owerri',
      lgas: [
        { id: 'imo-1', name: 'Aboh Mbaise' },
        { id: 'imo-2', name: 'Ahiazu Mbaise' },
        { id: 'imo-3', name: 'Ehime Mbano' },
        { id: 'imo-4', name: 'Ezinihitte' },
        { id: 'imo-5', name: 'Ideato North' },
        { id: 'imo-6', name: 'Ideato South' },
        { id: 'imo-7', name: 'Ihitte/Uboma' },
        { id: 'imo-8', name: 'Ikeduru' },
        { id: 'imo-9', name: 'Isiala Mbano' },
        { id: 'imo-10', name: 'Isu' },
        { id: 'imo-11', name: 'Mbaitoli' },
        { id: 'imo-12', name: 'Ngor Okpala' },
        { id: 'imo-13', name: 'Njaba' },
        { id: 'imo-14', name: 'Nkwerre' },
        { id: 'imo-15', name: 'Nwangele' },
        { id: 'imo-16', name: 'Obowo' },
        { id: 'imo-17', name: 'Oguta' },
        { id: 'imo-18', name: 'Ohaji/Egbema' },
        { id: 'imo-19', name: 'Okigwe' },
        { id: 'imo-20', name: 'Orlu' },
        { id: 'imo-21', name: 'Orsu' },
        { id: 'imo-22', name: 'Oru East' },
        { id: 'imo-23', name: 'Oru West' },
        { id: 'imo-24', name: 'Owerri Municipal' },
        { id: 'imo-25', name: 'Owerri North' },
        { id: 'imo-26', name: 'Owerri West' },
        { id: 'imo-27', name: 'Unuimo' },
      ]
    },
    {
      id: 'jigawa',
      name: 'Jigawa',
      capital: 'Dutse',
      lgas: [
        { id: 'jigawa-1', name: 'Auyo' },
        { id: 'jigawa-2', name: 'Babura' },
        { id: 'jigawa-3', name: 'Biriniwa' },
        { id: 'jigawa-4', name: 'Birnin Kudu' },
        { id: 'jigawa-5', name: 'Buji' },
        { id: 'jigawa-6', name: 'Dutse' },
        { id: 'jigawa-7', name: 'Gagarawa' },
        { id: 'jigawa-8', name: 'Garki' },
        { id: 'jigawa-9', name: 'Gumel' },
        { id: 'jigawa-10', name: 'Guri' },
        { id: 'jigawa-11', name: 'Gwaram' },
        { id: 'jigawa-12', name: 'Hadejia' },
        { id: 'jigawa-13', name: 'Jahun' },
        { id: 'jigawa-14', name: 'Kafin Hausa' },
        { id: 'jigawa-15', name: 'Kaugama' },
        { id: 'jigawa-16', name: 'Kazaure' },
        { id: 'jigawa-17', name: 'Kiri Kasamma' },
        { id: 'jigawa-18', name: 'Kiyawa' },
        { id: 'jigawa-19', name: 'Maigatari' },
        { id: 'jigawa-20', name: 'Malam Madori' },
        { id: 'jigawa-21', name: 'Miga' },
        { id: 'jigawa-22', name: 'Ringim' },
        { id: 'jigawa-23', name: 'Roni' },
        { id: 'jigawa-24', name: 'Saginu' },
        { id: 'jigawa-25', name: 'Yankwashi' },
      ]
    },
    {
      id: 'kaduna',
      name: 'Kaduna',
      capital: 'Kaduna',
      lgas: [
        { id: 'kaduna-1', name: 'Birnin Gwari' },
        { id: 'kaduna-2', name: 'Chikun' },
        { id: 'kaduna-3', name: 'Giwa' },
        { id: 'kaduna-4', name: 'Igabi' },
        { id: 'kaduna-5', name: 'Ikara' },
        { id: 'kaduna-6', name: 'Jaba' },
        { id: 'kaduna-7', name: 'Jema\'a' },
        { id: 'kaduna-8', name: 'Kachia' },
        { id: 'kaduna-9', name: 'Kaduna North' },
        { id: 'kaduna-10', name: 'Kaduna South' },
        { id: 'kaduna-11', name: 'Kagarko' },
        { id: 'kaduna-12', name: 'Kari' },
        { id: 'kaduna-13', name: 'Kaura' },
        { id: 'kaduna-14', name: 'Kauru' },
        { id: 'kaduna-15', name: 'Kubau' },
        { id: 'kaduna-16', name: 'Kudan' },
        { id: 'kaduna-17', name: 'Lere' },
        { id: 'kaduna-18', name: 'Makarfi' },
        { id: 'kaduna-19', name: 'Sabon Gari' },
        { id: 'kaduna-20', name: 'Sanga' },
        { id: 'kaduna-21', name: 'Soba' },
        { id: 'kaduna-22', name: 'Zaria' },
      ]
    },
    {
      id: 'kano',
      name: 'Kano',
      capital: 'Kano',
      lgas: [
        { id: 'kano-1', name: 'Albasu' },
        { id: 'kano-2', name: 'Bagwai' },
        { id: 'kano-3', name: 'Bebeji' },
        { id: 'kano-4', name: 'Bichi' },
        { id: 'kano-5', name: 'Bunkure' },
        { id: 'kano-6', name: 'Dala' },
        { id: 'kano-7', name: 'Dambatta' },
        { id: 'kano-8', name: 'Dawakin Kudu' },
        { id: 'kano-9', name: 'Dawakin Tofa' },
        { id: 'kano-10', name: 'Doguwa' },
        { id: 'kano-11', name: 'Fagge' },
        { id: 'kano-12', name: 'Gabasawa' },
        { id: 'kano-13', name: 'Garko' },
        { id: 'kano-14', name: 'Garun Mallam' },
        { id: 'kano-15', name: 'Gaya' },
        { id: 'kano-16', name: 'Gezawa' },
        { id: 'kano-17', name: 'Gwale' },
        { id: 'kano-18', name: 'Gwarzo' },
        { id: 'kano-19', name: 'Kabo' },
        { id: 'kano-20', name: 'Kano Municipal' },
        { id: 'kano-21', name: 'Karaye' },
        { id: 'kano-22', name: 'Kibiya' },
        { id: 'kano-23', name: 'Kiru' },
        { id: 'kano-24', name: 'Kumbotso' },
        { id: 'kano-25', name: 'Kunchi' },
        { id: 'kano-26', name: 'Kura' },
        { id: 'kano-27', name: 'Madobi' },
        { id: 'kano-28', name: 'Makoda' },
        { id: 'kano-29', name: 'Minjibir' },
        { id: 'kano-30', name: 'Nasarawa' },
        { id: 'kano-31', name: 'Rano' },
        { id: 'kano-32', name: 'Rimin Gado' },
        { id: 'kano-33', name: 'Rogo' },
        { id: 'kano-34', name: 'Shanono' },
        { id: 'kano-35', name: 'Sumaila' },
        { id: 'kano-36', name: 'Takai' },
        { id: 'kano-37', name: 'Tarauni' },
        { id: 'kano-38', name: 'Tofa' },
        { id: 'kano-39', name: 'Tsanyawa' },
        { id: 'kano-40', name: 'Tudun Wada' },
        { id: 'kano-41', name: 'Ungogo' },
        { id: 'kano-42', name: 'Warawa' },
        { id: 'kano-43', name: 'Wudil' },
      ]
    },
    {
      id: 'katsina',
      name: 'Katsina',
      capital: 'Katsina',
      lgas: [
        { id: 'katsina-1', name: 'Bakori' },
        { id: 'katsina-2', name: 'Batagarawa' },
        { id: 'katsina-3', name: 'Batsari' },
        { id: 'katsina-4', name: 'Baure' },
        { id: 'katsina-5', name: 'Bindawa' },
        { id: 'katsina-6', name: 'Charanchi' },
        { id: 'katsina-7', name: 'Dandume' },
        { id: 'katsina-8', name: 'Danja' },
        { id: 'katsina-9', name: 'Dan Musa' },
        { id: 'katsina-10', name: 'Daura' },
        { id: 'katsina-11', name: 'Dutsi' },
        { id: 'katsina-12', name: 'Dutsin-Ma' },
        { id: 'katsina-13', name: 'Faskari' },
        { id: 'katsina-14', name: 'Funtua' },
        { id: 'katsina-15', name: 'Ingawa' },
        { id: 'katsina-16', name: 'Jibia' },
        { id: 'katsina-17', name: 'Kafur' },
        { id: 'katsina-18', name: 'Kaita' },
        { id: 'katsina-19', name: 'Kankara' },
        { id: 'katsina-20', name: 'Kankia' },
        { id: 'katsina-21', name: 'Katsina' },
        { id: 'katsina-22', name: 'Kurfi' },
        { id: 'katsina-23', name: 'Kusada' },
        { id: 'katsina-24', name: 'Mai\'Adua' },
        { id: 'katsina-25', name: 'Malumfashi' },
        { id: 'katsina-26', name: 'Mani' },
        { id: 'katsina-27', name: 'Mashi' },
        { id: 'katsina-28', name: 'Matazu' },
        { id: 'katsina-29', name: 'Musawa' },
        { id: 'katsina-30', name: 'Rimi' },
        { id: 'katsina-31', name: 'Sabuwa' },
        { id: 'katsina-32', name: 'Safana' },
        { id: 'katsina-33', name: 'Sandamu' },
        { id: 'katsina-34', name: 'Zango' },
      ]
    },
    {
      id: 'kebbi',
      name: 'Kebbi',
      capital: 'Birnin Kebbi',
      lgas: [
        { id: 'kebbi-1', name: 'Aleiro' },
        { id: 'kebbi-2', name: 'Arewa' },
        { id: 'kebbi-3', name: 'Argungu' },
        { id: 'kebbi-4', name: 'Bagudo' },
        { id: 'kebbi-5', name: 'Birnin Kebbi' },
        { id: 'kebbi-6', name: 'Bunza' },
        { id: 'kebbi-7', name: 'Dandi' },
        { id: 'kebbi-8', name: 'D Wasagu' },
        { id: 'kebbi-9', name: 'Gwandu' },
        { id: 'kebbi-10', name: 'Jega' },
        { id: 'kebbi-11', name: 'Kalgo' },
        { id: 'kebbi-12', name: 'Koko/Besse' },
        { id: 'kebbi-13', name: 'Maiyama' },
        { id: 'kebbi-14', name: 'Ngaski' },
        { id: 'kebbi-15', name: 'Sakaba' },
        { id: 'kebbi-16', name: 'Shanga' },
        { id: 'kebbi-17', name: 'Suru' },
        { id: 'kebbi-18', name: 'Yauri' },
        { id: 'kebbi-19', name: 'Zuru' },
      ]
    },
    {
      id: 'kogi',
      name: 'Kogi',
      capital: 'Lokoja',
      lgas: [
        { id: 'kogi-1', name: 'Adavi' },
        { id: 'kogi-2', name: 'Ajaokuta' },
        { id: 'kogi-3', name: 'Ankpa' },
        { id: 'kogi-4', name: 'Bassa' },
        { id: 'kogi-5', name: 'Dekina' },
        { id: 'kogi-6', name: 'Ibaji' },
        { id: 'kogi-7', name: 'Idah' },
        { id: 'kogi-8', name: 'Igalamela-Odolu' },
        { id: 'kogi-9', name: 'Ijumu' },
        { id: 'kogi-10', name: 'Kabba/Bunu' },
        { id: 'kogi-11', name: 'Kotonkarfe' },
        { id: 'kogi-12', name: 'Lokoja' },
        { id: 'kogi-13', name: 'Mopamuro' },
        { id: 'kogi-14', name: 'Okehi' },
        { id: 'kogi-15', name: 'Okene' },
        { id: 'kogi-16', name: 'Olamaboro' },
        { id: 'kogi-17', name: 'Omala' },
        { id: 'kogi-18', name: 'Yagba East' },
        { id: 'kogi-19', name: 'Yagba West' },
      ]
    },
    {
      id: 'kwara',
      name: 'Kwara',
      capital: 'Ilorin',
      lgas: [
        { id: 'kwara-1', name: 'Asa' },
        { id: 'kwara-2', name: 'Baruten' },
        { id: 'kwara-3', name: 'Edu' },
        { id: 'kwara-4', name: 'Ekiti' },
        { id: 'kwara-5', name: 'Ifelodun' },
        { id: 'kwara-6', name: 'Ilorin East' },
        { id: 'kwara-7', name: 'Ilorin South' },
        { id: 'kwara-8', name: 'Ilorin West' },
        { id: 'kwara-9', name: 'Isin' },
        { id: 'kwara-10', name: 'Kaiama' },
        { id: 'kwara-11', name: 'Moro' },
        { id: 'kwara-12', name: 'Offa' },
        { id: 'kwara-13', name: 'Oke Ero' },
        { id: 'kwara-14', name: 'Oyun' },
        { id: 'kwara-15', name: 'Paki' },
        { id: 'kwara-16', name: 'Patigi' },
        { id: 'kwara-17', name: 'Sakpe' },
        { id: 'kwara-18', name: 'Surulere' },
      ]
    },
    {
      id: 'lagos',
      name: 'Lagos',
      capital: 'Ikeja',
      lgas: [
        { id: 'lagos-1', name: 'Agege' },
        { id: 'lagos-2', name: 'Ajeromi-Ifelodun' },
        { id: 'lagos-3', name: 'Alimosho' },
        { id: 'lagos-4', name: 'Amuwo-Odofin' },
        { id: 'lagos-5', name: 'Apapa' },
        { id: 'lagos-6', name: 'Badagry' },
        { id: 'lagos-7', name: 'Epe' },
        { id: 'lagos-8', name: 'Eti Osa' },
        { id: 'lagos-9', name: 'Ibeju-Lekki' },
        { id: 'lagos-10', name: 'Ifako-Ijaye' },
        { id: 'lagos-11', name: 'Ikeja' },
        { id: 'lagos-12', name: 'Ikorodu' },
        { id: 'lagos-13', name: 'Kosofe' },
        { id: 'lagos-14', name: 'Lagos Island' },
        { id: 'lagos-15', name: 'Lagos Mainland' },
        { id: 'lagos-16', name: 'Mushin' },
        { id: 'lagos-17', name: 'Ojo' },
        { id: 'lagos-18', name: 'Oshodi-Isolo' },
        { id: 'lagos-19', name: 'Shomolu' },
        { id: 'lagos-20', name: 'Surulere' },
      ]
    },
    {
      id: 'nasarawa',
      name: 'Nasarawa',
      capital: 'Lafia',
      lgas: [
        { id: 'nasarawa-1', name: 'Akwanga' },
        { id: 'nasarawa-2', name: 'Awe' },
        { id: 'nasarawa-3', name: 'Doma' },
        { id: 'nasarawa-4', name: 'Karu' },
        { id: 'nasarawa-5', name: 'Keana' },
        { id: 'nasarawa-6', name: 'Keffi' },
        { id: 'nasarawa-7', name: 'Kokona' },
        { id: 'nasarawa-8', name: 'Lafia' },
        { id: 'nasarawa-9', name: 'Nasarawa' },
        { id: 'nasarawa-10', name: 'Nasarawa Egon' },
        { id: 'nasarawa-11', name: 'Toto' },
        { id: 'nasarawa-12', name: 'Wamba' },
      ]
    },
    {
      id: 'niger',
      name: 'Niger',
      capital: 'Minna',
      lgas: [
        { id: 'niger-1', name: 'Agaga' },
        { id: 'niger-2', name: 'Bida' },
        { id: 'niger-3', name: 'Borgu' },
        { id: 'niger-4', name: 'Bosia' },
        { id: 'niger-5', name: 'Chanchaga' },
        { id: 'niger-6', name: 'Edatti' },
        { id: 'niger-7', name: 'Gbako' },
        { id: 'niger-8', name: 'Katcha' },
        { id: 'niger-9', name: 'Kontagora' },
        { id: 'niger-10', name: 'Lapai' },
        { id: 'niger-11', name: 'Lavun' },
        { id: 'niger-12', name: 'Magama' },
        { id: 'niger-13', name: 'Mariga' },
        { id: 'niger-14', name: 'Mashegu' },
        { id: 'niger-15', name: 'Moya' },
        { id: 'niger-16', name: 'Muya' },
        { id: 'niger-17', name: 'Paikoro' },
        { id: 'niger-18', name: 'Rijau' },
        { id: 'niger-19', name: 'Shiroro' },
        { id: 'niger-20', name: 'Suleja' },
        { id: 'niger-21', name: 'Tafa' },
        { id: 'niger-22', name: 'Wushishi' },
      ]
    },
    {
      id: 'ogun',
      name: 'Ogun',
      capital: 'Abeokuta',
      lgas: [
        { id: 'ogun-1', name: 'Abeokuta North' },
        { id: 'ogun-2', name: 'Abeokuta South' },
        { id: 'ogun-3', name: 'Ado-Odo/Ota' },
        { id: 'ogun-4', name: 'Yewa North' },
        { id: 'ogun-5', name: 'Yewa South' },
        { id: 'ogun-6', name: 'Ewekoro' },
        { id: 'ogun-7', name: 'Ifo' },
        { id: 'ogun-8', name: 'Sagamu' },
        { id: 'ogun-9', name: 'Obafemi Owode' },
        { id: 'ogun-10', name: 'Odeda' },
        { id: 'ogun-11', name: 'Odogbolu' },
        { id: 'ogun-12', name: 'Remo North' },
        { id: 'ogun-13', name: 'Remo South' },
        { id: 'ogun-14', name: 'Ikenne' },
        { id: 'ogun-15', name: 'Shagamu' },
        { id: 'ogun-16', name: 'Imeko Afon' },
        { id: 'ogun-17', name: 'Ijebu East' },
        { id: 'ogun-18', name: 'Ijebu North' },
        { id: 'ogun-19', name: 'Ijebu North East' },
        { id: 'ogun-20', name: 'Ijebu Ode' },
        { id: 'ogun-21', name: 'Ikitifi' },
        { id: 'ogun-22', name: 'Ipokia' },
      ]
    },
    {
      id: 'ondo',
      name: 'Ondo',
      capital: 'Akure',
      lgas: [
        { id: 'ondo-1', name: 'Akoko North East' },
        { id: 'ondo-2', name: 'Akoko North West' },
        { id: 'ondo-3', name: 'Akoko South East' },
        { id: 'ondo-4', name: 'Akoko South West' },
        { id: 'ondo-5', name: 'Akure North' },
        { id: 'ondo-6', name: 'Akure South' },
        { id: 'ondo-7', name: 'Ese Odo' },
        { id: 'ondo-8', name: 'Idanre' },
        { id: 'ondo-9', name: 'Ifedore' },
        { id: 'ondo-10', name: 'Ilaje' },
        { id: 'ondo-11', name: 'Ile Oluji/Okeigbo' },
        { id: 'ondo-12', name: 'Irele' },
        { id: 'ondo-13', name: 'Odigbo' },
        { id: 'ondo-14', name: 'Okitipupa' },
        { id: 'ondo-15', name: 'Ondo East' },
        { id: 'ondo-16', name: 'Ondo West' },
        { id: 'ondo-17', name: 'Ose' },
        { id: 'ondo-18', name: 'Owo' },
      ]
    },
    {
      id: 'osun',
      name: 'Osun',
      capital: 'Osogbo',
      lgas: [
        { id: 'osun-1', name: 'Atakunmosa East' },
        { id: 'osun-2', name: 'Atakunmosa West' },
        { id: 'osun-3', name: 'Aiyedaade' },
        { id: 'osun-4', name: 'Aiyedire' },
        { id: 'osun-5', name: 'Atakunmosa' },
        { id: 'osun-6', name: 'Boluwaduro' },
        { id: 'osun-7', name: 'Boripe' },
        { id: 'osun-8', name: 'Ede South' },
        { id: 'osun-9', name: 'Ede North' },
        { id: 'osun-10', name: 'Ejigbo' },
        { id: 'osun-11', name: 'Ede' },
        { id: 'osun-12', name: 'Ife Central' },
        { id: 'osun-13', name: 'Ife East' },
        { id: 'osun-14', name: 'Ife North' },
        { id: 'osun-15', name: 'Ife South' },
        { id: 'osun-16', name: 'Ilesa East' },
        { id: 'osun-17', name: 'Ilesa West' },
        { id: 'osun-18', name: 'Irepodun' },
        { id: 'osun-19', name: 'Irewole' },
        { id: 'osun-20', name: 'Isokan' },
        { id: 'osun-21', name: 'Iwo' },
        { id: 'osun-22', name: 'Obokun' },
        { id: 'osun-23', name: 'Odo Otin' },
        { id: 'osun-24', name: 'Ola Oluwa' },
        { id: 'osun-25', name: 'Olorunda' },
        { id: 'osun-26', name: 'Oriade' },
        { id: 'osun-27', name: 'Orolu' },
        { id: 'osun-28', name: 'Osogbo' },
      ]
    },
    {
      id: 'oyo',
      name: 'Oyo',
      capital: 'Ibadan',
      lgas: [
        { id: 'oyo-1', name: 'Afijio' },
        { id: 'oyo-2', name: 'Akinyele' },
        { id: 'oyo-3', name: 'Atiba' },
        { id: 'oyo-4', name: 'Atisbo' },
        { id: 'oyo-5', name: 'Egbeda' },
        { id: 'oyo-6', name: 'Ibadan North' },
        { id: 'oyo-7', name: 'Ibadan North East' },
        { id: 'oyo-8', name: 'Ibadan North West' },
        { id: 'oyo-9', name: 'Ibadan South East' },
        { id: 'oyo-10', name: 'Ibadan South West' },
        { id: 'oyo-11', name: 'Ibarapa Central' },
        { id: 'oyo-12', name: 'Ibarapa East' },
        { id: 'oyo-13', name: 'Ibarapa North' },
        { id: 'oyo-14', name: 'Ido' },
        { id: 'oyo-15', name: 'Iseyin' },
        { id: 'oyo-16', name: 'Itesiwaju' },
        { id: 'oyo-17', name: 'Iwajowa' },
        { id: 'oyo-18', name: 'Kajola' },
        { id: 'oyo-19', name: 'Lagelu' },
        { id: 'oyo-20', name: 'Ogbomosho North' },
        { id: 'oyo-21', name: 'Ogbomosho South' },
        { id: 'oyo-22', name: 'Ogo Oluwa' },
        { id: 'oyo-23', name: 'Olorunsogo' },
        { id: 'oyo-24', name: 'Oluyole' },
        { id: 'oyo-25', name: 'Ona Ara' },
        { id: 'oyo-26', name: 'Orelope' },
        { id: 'oyo-27', name: 'Ori Ire' },
        { id: 'oyo-28', name: 'Oyo East' },
        { id: 'oyo-29', name: 'Oyo West' },
        { id: 'oyo-30', name: 'Saki East' },
        { id: 'oyo-31', name: 'Saki West' },
        { id: 'oyo-32', name: 'Surulere' },
      ]
    },
    {
      id: 'plateau',
      name: 'Plateau',
      capital: 'Jos',
      lgas: [
        { id: 'plateau-1', name: 'Barkin Ladi' },
        { id: 'plateau-2', name: 'Bassa' },
        { id: 'plateau-3', name: 'Bukuru' },
        { id: 'plateau-4', name: 'Jos East' },
        { id: 'plateau-5', name: 'Jos North' },
        { id: 'plateau-6', name: 'Jos South' },
        { id: 'plateau-7', name: 'Kanam' },
        { id: 'plateau-8', name: 'Kanke' },
        { id: 'plateau-9', name: 'Langtang North' },
        { id: 'plateau-10', name: 'Langtang South' },
        { id: 'plateau-11', name: 'Mangu' },
        { id: 'plateau-12', name: 'Mikang' },
        { id: 'plateau-13', name: 'Pankshin' },
        { id: 'plateau-14', name: 'Qua\'an Pan' },
        { id: 'plateau-15', name: 'Riyom' },
        { id: 'plateau-16', name: 'Shendam' },
        { id: 'plateau-17', name: 'Wase' },
      ]
    },
    {
      id: 'rivers',
      name: 'Rivers',
      capital: 'Port Harcourt',
      lgas: [
        { id: 'rivers-1', name: 'Abua/Odual' },
        { id: 'rivers-2', name: 'Ahoada East' },
        { id: 'rivers-3', name: 'Ahoada West' },
        { id: 'rivers-4', name: 'Akuku Toru' },
        { id: 'rivers-5', name: 'Andoni' },
        { id: 'rivers-6', name: 'Asari-Toru' },
        { id: 'rivers-7', name: 'Bonny' },
        { id: 'rivers-8', name: 'Degema' },
        { id: 'rivers-9', name: 'Eleme' },
        { id: 'rivers-10', name: 'Emohua' },
        { id: 'rivers-11', name: 'Etche' },
        { id: 'rivers-12', name: 'Gokana' },
        { id: 'rivers-13', name: 'Ikwerre' },
        { id: 'rivers-14', name: 'Khana' },
        { id: 'rivers-15', name: 'Obio/Akpo' },
        { id: 'rivers-16', name: 'Ogba/Egbema/Ndoni' },
        { id: 'rivers-17', name: 'Ogu/Bolo' },
        { id: 'rivers-18', name: 'Okrika' },
        { id: 'rivers-19', name: 'Omuma' },
        { id: 'rivers-20', name: 'Opobo/Nkoro' },
        { id: 'rivers-21', name: 'Port Harcourt' },
        { id: 'rivers-22', name: 'Tai' },
      ]
    },
    {
      id: 'sokoto',
      name: 'Sokoto',
      capital: 'Sokoto',
      lgas: [
        { id: 'sokoto-1', name: 'Bodinga' },
        { id: 'sokoto-2', name: 'Dange' },
        { id: 'sokoto-3', name: 'Gada' },
        { id: 'sokoto-4', name: 'Goronyo' },
        { id: 'sokoto-5', name: 'Gudu' },
        { id: 'sokoto-6', name: 'Gwadabawa' },
        { id: 'sokoto-7', name: 'Illela' },
        { id: 'sokoto-8', name: 'Isa' },
        { id: 'sokoto-9', name: 'Kebbe' },
        { id: 'sokoto-10', name: 'Kware' },
        { id: 'sokoto-11', name: 'Raba' },
        { id: 'sokoto-12', name: 'Sabon Birni' },
        { id: 'sokoto-13', name: 'Shagari' },
        { id: 'sokoto-14', name: 'Silame' },
        { id: 'sokoto-15', name: 'Sokoto North' },
        { id: 'sokoto-16', name: 'Sokoto South' },
        { id: 'sokoto-17', name: 'Tambuwal' },
        { id: 'sokoto-18', name: 'Tangaza' },
        { id: 'sokoto-19', name: 'T灯in' },
        { id: 'sokoto-20', name: 'Wamako' },
        { id: 'sokoto-21', name: 'Wurno' },
        { id: 'sokoto-22', name: 'Yabo' },
      ]
    },
    {
      id: 'taraba',
      name: 'Taraba',
      capital: 'Jalingo',
      lgas: [
        { id: 'taraba-1', name: 'Ardo Kola' },
        { id: 'taraba-2', name: 'Bali' },
        { id: 'taraba-3', name: 'Donga' },
        { id: 'taraba-4', name: 'Gashaka' },
        { id: 'taraba-5', name: 'Gassol' },
        { id: 'taraba-6', name: 'Ibi' },
        { id: 'taraba-7', name: 'Jalingo' },
        { id: 'taraba-8', name: 'Karim Lamido' },
        { id: 'taraba-9', name: 'Kumi' },
        { id: 'taraba-10', name: 'Lau' },
        { id: 'taraba-11', name: 'Sardauna' },
        { id: 'taraba-12', name: 'Takum' },
        { id: 'taraba-13', name: 'Ussa' },
        { id: 'taraba-14', name: 'Wukari' },
        { id: 'taraba-15', name: 'Yorro' },
        { id: 'taraba-16', name: 'Zing' },
      ]
    },
    {
      id: 'yobe',
      name: 'Yobe',
      capital: 'Damaturu',
      lgas: [
        { id: 'yobe-1', name: 'Bade' },
        { id: 'yobe-2', name: 'Bursari' },
        { id: 'yobe-3', name: 'Damaturu' },
        { id: 'yobe-4', name: 'Fika' },
        { id: 'yobe-5', name: 'Fune' },
        { id: 'yobe-6', name: 'Geidam' },
        { id: 'yobe-7', name: 'Gujba' },
        { id: 'yobe-8', name: 'Gulani' },
        { id: 'yobe-9', name: 'Jakusko' },
        { id: 'yobe-10', name: 'Karasuwa' },
        { id: 'yobe-11', name: 'Karawa' },
        { id: 'yobe-12', name: 'Machina' },
        { id: 'yobe-13', name: 'Nangere' },
        { id: 'yobe-14', name: 'Nguru' },
        { id: 'yobe-15', name: 'Potiskum' },
        { id: 'yobe-16', name: 'Tarmuwa' },
        { id: 'yobe-17', name: 'Yusufari' },
      ]
    },
    {
      id: 'zamfara',
      name: 'Zamfara',
      capital: 'Gusau',
      lgas: [
        { id: 'zamfara-1', name: 'Anka' },
        { id: 'zamfara-2', name: 'Bakura' },
        { id: 'zamfara-3', name: 'Birnin Magaji/Kiyaw' },
        { id: 'zamfara-4', name: 'Bukkuyum' },
        { id: 'zamfara-5', name: 'Bungudu' },
        { id: 'zamfara-6', name: 'Gummi' },
        { id: 'zamfara-7', name: 'Gusau' },
        { id: 'zamfara-8', name: 'Kaura Namoda' },
        { id: 'zamfara-9', name: 'Maradun' },
        { id: 'zamfara-10', name: 'Maru' },
        { id: 'zamfara-11', name: 'Shinkafi' },
        { id: 'zamfara-12', name: 'Talata Mafara' },
        { id: 'zamfara-13', name: 'Tsafe' },
        { id: 'zamfara-14', name: 'Zurmi' },
      ]
    }
  ]
};

// Helper functions
export function getAllStates(): State[] {
  return nigeriaLocationData.states;
}

export function getStateById(stateId: string): State | undefined {
  return nigeriaLocationData.states.find(s => s.id === stateId);
}

export function getLgasByStateId(stateId: string): LocalGovernmentArea[] {
  const state = getStateById(stateId);
  return state?.lgas || [];
}

export function getTotalLgas(): number {
  return nigeriaLocationData.states.reduce((acc, state) => acc + state.lgas.length, 0);
}

export function formatLocation(country: string, state: string, lga: string): string {
  return `${lga}, ${state}, ${country}`;
}

// Country list for dropdown
export const countries: Country[] = [
  nigeriaLocationData,
  {
    id: 'us',
    name: 'United States',
    code: 'US',
    states: []
  },
  {
    id: 'uk',
    name: 'United Kingdom',
    code: 'UK',
    states: []
  },
  {
    id: 'ca',
    name: 'Canada',
    code: 'CA',
    states: []
  }
];