// =====================================================
// INNOVASCI OPEN UNIVERSITY - DEMO SEED DATA
// Complete Test Credentials for All Roles (Password: Demo@123)
// =====================================================

import { User, Student, AcademicStaff, UserRole } from '@/types';

// Universal demo password for all test accounts
export const DEMO_PASSWORD = 'Demo@123';

// =====================================================
// MANAGEMENT PORTAL - DEMO USERS (16 roles)
// =====================================================

export const DEMO_MANAGEMENT_USERS: Array<User & { password: string; role: any }> = [
  {
    id: 'mgmt-001',
    email: 'vc@innovasci.edu.ng',
    fullName: 'Prof. Adeyemi Oluwaseun',
    role: 'vice_chancellor',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 802 123 4567',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-002',
    email: 'deputy.vc.academic@innovasci.edu.ng',
    fullName: 'Dr. Chioma Nnamdi',
    role: 'deputy_vc_academic',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 803 987 6543',
    createdAt: new Date('2024-01-16').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-003',
    email: 'deputy.vc.admin@innovasci.edu.ng',
    fullName: 'Mr. Ibrahim Kafar',
    role: 'deputy_vc_admin',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 804 555 1111',
    createdAt: new Date('2024-01-17').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-004',
    email: 'deputy.vc.research@innovasci.edu.ng',
    fullName: 'Prof. Ngozi Okonkwo',
    role: 'deputy_vc_research',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 805 222 3333',
    createdAt: new Date('2024-01-18').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-005',
    email: 'registrar@innovasci.edu.ng',
    fullName: 'Mrs. Amara Eze',
    role: 'registrar',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 806 444 5555',
    createdAt: new Date('2024-01-19').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-006',
    email: 'bursar@innovasci.edu.ng',
    fullName: 'Mr. Kunle Adebayo',
    role: 'bursar',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 807 666 7777',
    createdAt: new Date('2024-01-20').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-007',
    email: 'director.admission@innovasci.edu.ng',
    fullName: 'Dr. Folake Olufunke',
    role: 'director_admission',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 808 888 9999',
    createdAt: new Date('2024-01-21').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-008',
    email: 'director.examination@innovasci.edu.ng',
    fullName: 'Mr. Tunde Olayinka',
    role: 'director_examination',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 809 111 2222',
    createdAt: new Date('2024-01-22').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-009',
    email: 'director.study.centre@innovasci.edu.ng',
    fullName: 'Mrs. Rita Adekunle',
    role: 'director_study_centre',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 810 333 4444',
    createdAt: new Date('2024-01-23').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-010',
    email: 'director.lss@innovasci.edu.ng',
    fullName: 'Dr. Emeka Uche',
    role: 'director_lss',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 811 555 6666',
    createdAt: new Date('2024-01-24').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-011',
    email: 'director.odfel@innovasci.edu.ng',
    fullName: 'Prof. Bola Oyewole',
    role: 'director_odfel',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 812 777 8888',
    createdAt: new Date('2024-01-25').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-012',
    email: 'director.ict@innovasci.edu.ng',
    fullName: 'Mr. Chinedu Okoro',
    role: 'director_ict',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 813 999 0000',
    createdAt: new Date('2024-01-26').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-013',
    email: 'director.qa@innovasci.edu.ng',
    fullName: 'Dr. Grace Udeh',
    role: 'director_quality_assurance',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 814 111 2222',
    createdAt: new Date('2024-01-27').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-014',
    email: 'director.welfare@innovasci.edu.ng',
    fullName: 'Mrs. Yetunde Adepitan',
    role: 'director_student_welfare',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 815 333 4444',
    createdAt: new Date('2024-01-28').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-015',
    email: 'director.research@innovasci.edu.ng',
    fullName: 'Prof. Kwame Boateng',
    role: 'director_research',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 816 555 6666',
    createdAt: new Date('2024-01-29').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
  {
    id: 'mgmt-016',
    email: 'super.admin@innovasci.edu.ng',
    fullName: 'System Administrator',
    role: 'super_admin',
    portal: 'management',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 817 777 8888',
    createdAt: new Date('2024-01-30').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
  },
];

// =====================================================
// ACADEMIC PORTAL - DEMO USERS (11 roles)
// =====================================================

export const DEMO_ACADEMIC_USERS: Array<AcademicStaff & { password: string }> = [
  {
    id: 'acad-001',
    email: 'dean.undergraduate@innovasci.edu.ng',
    fullName: 'Prof. Eniola Rotimi',
    role: 'dean_undergraduate',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 820 111 2222',
    createdAt: new Date('2024-02-01').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    schoolId: 'school-001',
    schoolName: 'School of Undergraduate Studies',
  },
  {
    id: 'acad-002',
    email: 'dean.postgraduate@innovasci.edu.ng',
    fullName: 'Prof. Adebayo Olumide',
    role: 'dean_postgraduate',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 821 333 4444',
    createdAt: new Date('2024-02-02').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    schoolId: 'school-002',
    schoolName: 'School of Postgraduate Studies',
  },
  {
    id: 'acad-003',
    email: 'hod.maths@innovasci.edu.ng',
    fullName: 'Dr. Hakeem Ibrahim',
    role: 'head_of_department',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 822 555 6666',
    createdAt: new Date('2024-02-03').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    departmentId: 'dept-001',
    departmentName: 'Department of Mathematics',
  },
  {
    id: 'acad-004',
    email: 'coord.bsc.cs@innovasci.edu.ng',
    fullName: 'Dr. Okafor Chinedu',
    role: 'programme_coordinator_bsc',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 823 777 8888',
    createdAt: new Date('2024-02-04').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    programmeId: 'prog-001',
    programmeName: 'BSc Computer Science',
  },
  {
    id: 'acad-005',
    email: 'coord.pgd.biz@innovasci.edu.ng',
    fullName: 'Dr. Stella Okonkwo',
    role: 'programme_coordinator_pgd',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 824 999 0000',
    createdAt: new Date('2024-02-05').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    programmeId: 'prog-002',
    programmeName: 'PGD Business Administration',
  },
  {
    id: 'acad-006',
    email: 'coord.msc.eng@innovasci.edu.ng',
    fullName: 'Prof. Segun Adeyemo',
    role: 'programme_coordinator_msc',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 825 111 2222',
    createdAt: new Date('2024-02-06').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    programmeId: 'prog-003',
    programmeName: 'MSc Engineering',
  },
  {
    id: 'acad-007',
    email: 'coord.phd.bio@innovasci.edu.ng',
    fullName: 'Prof. Jumoke Adeyinka',
    role: 'programme_coordinator_phd',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 826 333 4444',
    createdAt: new Date('2024-02-07').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    programmeId: 'prog-004',
    programmeName: 'PhD Biology',
  },
  {
    id: 'acad-008',
    email: 'etutor.cs101@innovasci.edu.ng',
    fullName: 'Mr. Oluwaseun Olalekan',
    role: 'e_tutor',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 827 555 6666',
    createdAt: new Date('2024-02-08').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    specialization: 'Computer Science',
  },
  {
    id: 'acad-009',
    email: 'instructional.designer@innovasci.edu.ng',
    fullName: 'Mrs. Peju Owolabi',
    role: 'instructional_designer',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 828 777 8888',
    createdAt: new Date('2024-02-09').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    specialization: 'Educational Technology',
  },
  {
    id: 'acad-010',
    email: 'supervisor.phd@innovasci.edu.ng',
    fullName: 'Prof. Tunde Adejumo',
    role: 'supervisor',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 829 999 0000',
    createdAt: new Date('2024-02-10').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    specialization: 'Advanced Research',
  },
  {
    id: 'acad-011',
    email: 'research.fellow@innovasci.edu.ng',
    fullName: 'Dr. Akinbode Femi',
    role: 'research_fellow',
    portal: 'academic',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 830 111 2222',
    createdAt: new Date('2024-02-11').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    specialization: 'Interdisciplinary Research',
  },
];

// =====================================================
// STUDENT PORTAL - DEMO USERS
// =====================================================

export const DEMO_STUDENT_USERS: Array<Student & { password: string }> = [
  {
    id: 'student-001',
    email: 'student.bsc.001@innovasci.edu.ng',
    fullName: 'Chioma Nwankor',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 901 111 2222',
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/0001',
    degreeType: 'bsc',
    level: 200,
    semester: 1,
    academicStatus: 'active',
    paymentStatus: 'paid',
  },
  {
    id: 'student-002',
    email: 'student.bsc.002@innovasci.edu.ng',
    fullName: 'Amara Obiagwu',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 902 333 4444',
    createdAt: new Date('2024-03-02').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/0002',
    degreeType: 'bsc',
    level: 300,
    semester: 2,
    academicStatus: 'active',
    paymentStatus: 'paid',
  },
  {
    id: 'student-003',
    email: 'student.bsc.003@innovasci.edu.ng',
    fullName: 'Oluwatoyin Adebisi',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 903 555 6666',
    createdAt: new Date('2024-03-03').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/0003',
    degreeType: 'bsc',
    level: 400,
    semester: 1,
    academicStatus: 'active',
    paymentStatus: 'partial',
  },
  {
    id: 'student-004',
    email: 'student.pgd.001@innovasci.edu.ng',
    fullName: 'Dr. Kanayo Ejiofor',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 904 777 8888',
    createdAt: new Date('2024-04-01').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/P001',
    degreeType: 'pgd',
    level: 100,
    semester: 1,
    academicStatus: 'active',
    paymentStatus: 'paid',
  },
  {
    id: 'student-005',
    email: 'student.msc.001@innovasci.edu.ng',
    fullName: 'Bolaji Owolabi',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 905 999 0000',
    createdAt: new Date('2024-04-02').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/M001',
    degreeType: 'msc',
    level: 100,
    semester: 2,
    academicStatus: 'active',
    paymentStatus: 'paid',
  },
  {
    id: 'student-006',
    email: 'student.phd.001@innovasci.edu.ng',
    fullName: 'Prof. Ikechukwu Umeala',
    role: 'student',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 906 111 2222',
    createdAt: new Date('2024-04-03').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: true,
    admissionNumber: 'IOU/2024/PhD001',
    degreeType: 'phd',
    level: 100,
    semester: 1,
    academicStatus: 'active',
    paymentStatus: 'unpaid',
  },
];

// =====================================================
// APPLICANT PORTAL - DEMO USERS
// =====================================================

export const DEMO_APPLICANT_USERS: Array<User & { password: string }> = [
  {
    id: 'applicant-001',
    email: 'applicant.001@email.com',
    fullName: 'Akunna Okafor',
    role: 'applicant',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 910 111 2222',
    createdAt: new Date('2024-05-01').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: false,
  },
  {
    id: 'applicant-002',
    email: 'applicant.002@email.com',
    fullName: 'Samuel Adebowale',
    role: 'applicant',
    portal: 'student',
    password: DEMO_PASSWORD,
    avatar: undefined,
    phone: '+234 911 333 4444',
    createdAt: new Date('2024-05-02').toISOString(),
    updatedAt: new Date('2024-06-20').toISOString(),
    isActive: true,
    isVerified: false,
  },
];

// =====================================================
// COMBINED DEMO DATA
// =====================================================

export const ALL_DEMO_USERS = [
  ...DEMO_MANAGEMENT_USERS,
  ...DEMO_ACADEMIC_USERS,
  ...DEMO_STUDENT_USERS,
  ...DEMO_APPLICANT_USERS,
];

// =====================================================
// HELPER FUNCTIONS FOR DEMO DATA
// =====================================================

/**
 * Get demo user by email
 */
export function getDemoUserByEmail(email: string): typeof ALL_DEMO_USERS[0] | undefined {
  return ALL_DEMO_USERS.find(user => user.email.toLowerCase() === email.toLowerCase());
}

/**
 * Get demo user by role
 */
export function getDemoUsersByRole(role: UserRole) {
  return ALL_DEMO_USERS.filter(user => user.role === role);
}

/**
 * Verify demo credentials
 */
export function verifyDemoCredentials(email: string, password: string): typeof ALL_DEMO_USERS[0] | null {
  const user = getDemoUserByEmail(email);
  if (user && user.password === password) {
    // Return user without password
    const { password: _, ...userWithoutPassword } = user;
    return userWithoutPassword as any;
  }
  return null;
}

/**
 * Get credentials summary for documentation
 */
export function getCredentialsSummary() {
  return {
    totalUsers: ALL_DEMO_USERS.length,
    managementPortal: DEMO_MANAGEMENT_USERS.length,
    academicPortal: DEMO_ACADEMIC_USERS.length,
    studentPortal: DEMO_STUDENT_USERS.length,
    applicantPortal: DEMO_APPLICANT_USERS.length,
    universalPassword: DEMO_PASSWORD,
    allCredentials: ALL_DEMO_USERS.map(user => ({
      email: user.email,
      fullName: user.fullName,
      role: user.role,
      portal: user.portal,
    })),
  };
}
